### ISSUE TITLE
Can We Combine Assets To The Group Name

### ISSUE THREAD

**Issue by GrahamCampbell** [lightgear/asset#6]
At the moment, correct me if i'm from, we can only combine assets to one file name. Would it be possible to combine groups to `groupname.css` instead of `application.css`, and the same for the javascript? I am not saying we should replace the existing functionality, but perhaps have a config option for it.

**Comment by ralf57** [comment]
dc6be6181dda should do what you need

**Comment by GrahamCampbell** [comment]
Thanks! Any news on when the develop branch will be ready for merging into the master?
Also, will that branch be becoming V1.3, or V2.0?

**Comment by ralf57** [comment]
That will be 2.0 because of the API changes. I have also planned to add tests and a major refactor to have dedicated classes (Publisher and Processor). Now I need to find some time for this.

**Comment by GrahamCampbell** [comment]
Sounds great!
